# Generated by Django 6.0.3 on 2026-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to='galeria/')),
                ('categoria', models.CharField(choices=[('grafica', 'Gráfica'), ('textil', 'Têxtil'), ('outro', 'Outro')], max_length=20)),
                ('destaque', models.BooleanField(default=False)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('visivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('grafica', 'Gráfica'), ('textil', 'Têxtil')], max_length=20)),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone (ex: fas fa-print)', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
